In [59]:
%run reconstruct3D.py

map = reconstructed3D(ret = np.load('./calibration/camera_params/ret.npy'),
                      K = np.load('./calibration/camera_params/K.npy'),
                      dist = np.load('./calibration/camera_params/dist.npy'),
                      focal_length = np.load('./calibration/camera_params/FocalLength.npy'),
                      output_file = 'reconstruct1.ply')
map.load_images('Left3_.jpg','Right3_.jpg')
map.see_everything()
map.add_to_base()

In [60]:
map.write_output_data()

In [61]:
#map.clear_data()

In [62]:
map.load_images('Left3.jpg','Right3.jpg')
map.see_everything()
#map.add_to_base()

In [63]:
#######################################################################

In [64]:
%run pinhole_camera_and_VO.py

##setup link with database and camera
img_dir = 'dataset/images/'
#https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html
K = np.load('./calibration/camera_params/K.npy')
d = np.load('./calibration/camera_params/dist.npy')
cam = PinholeCamera(2592.0, 1944.0, K[0][0], K[1][1], K[0][2], K[1][2], d)

In [65]:
vo = VisualOdometry(cam)
traj = np.zeros((600,600,3), dtype=np.uint8)
predicted, actual = [],[]
img = cv2.imread('Left3_.jpg', 0)
vo.update(img)

In [66]:
img = cv2.imread('Left3.jpg', 0)
vo.update(img)

In [67]:
R = vo.cur_R

In [68]:
t = vo.cur_t

In [69]:
a = map.cur_map_points

In [70]:
R = R.transpose()

In [71]:
I = a.dot(R)

In [72]:
len(a)

55759

In [73]:
import numpy as np

In [74]:
T = np.zeros(len(a))
T

array([0., 0., 0., ..., 0., 0., 0.])

In [75]:
T = np.array([[t[0][0], t[1][0], t[2][0]] for i in T])
T[0]

array([-0.44858395,  0.37775362,  0.80998435])

In [76]:
I = I + T

In [77]:
I

array([[  24.77107269,   12.95508721,  -78.9129093 ],
       [  28.08464275,   10.36611494,  -83.30807437],
       [  27.97404755,   11.05480289,  -84.0246479 ],
       ...,
       [-216.32803925,   87.33386509, -323.28675346],
       [-216.89518939,   88.45957398, -323.51284858],
       [-218.37545048,   90.45932579, -322.75798572]])

In [78]:
map.cur_map_points = I

In [79]:
map.add_to_base()

In [80]:
map.output_file = 'plus.ply'

In [81]:
map.write_output_data()