In [1]:
%run reconstruct3D.py

map = reconstructed3D(ret = np.load('./calibration/camera_params/ret.npy'),
                      K = np.load('./calibration/camera_params/K.npy'),
                      dist = np.load('./calibration/camera_params/dist.npy'),
                      focal_length = np.load('./calibration/camera_params/FocalLength.npy'),
                      output_file = 'reconstruct.ply')
map.load_images('Left.jpg','Right.jpg')
map.see_everything()
map.add_to_base()

In [2]:
map.write_output_data()

In [3]:
map.load_images('Left1.jpg','Right1.jpg')
map.see_everything()
#map.add_to_base()

In [ ]:
#######################################################################

In [4]:
%run pinhole_camera_and_VO.py

##setup link with database and camera
img_dir = 'dataset/images/'
#https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html
K = np.load('./calibration/camera_params/K.npy')
cam = PinholeCamera(2592.0, 1944.0, K[0][0], K[1][1], K[0][2], K[1][2])

In [5]:
vo = VisualOdometry(cam)
traj = np.zeros((600,600,3), dtype=np.uint8)
predicted, actual = [],[]
img = cv2.imread('Left.jpg', 0)
vo.update(img)

In [6]:
img = cv2.imread('Left1.jpg', 0)
vo.update(img)

In [7]:
R = vo.cur_R

In [8]:
t = vo.cur_t
t[0][0]

0.18128488250538383

In [9]:
a = map.cur_map_points

In [10]:
I = a.dot(R)

In [11]:
len(a)

57612

In [12]:
import numpy as np

In [13]:
T = np.zeros(len(a))
T

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
T = np.array([[t[0][0], t[1][0], t[2][0]] for i in T])
T[0]

array([0.18128488, 0.3217993 , 0.92929059])

In [15]:
I = I + T

In [16]:
I

array([[  62.69669283,    1.96856154,   -6.69382843],
       [  63.68900089,    1.99470063,   -6.81483032],
       [  64.68130895,    2.02083971,   -6.93583221],
       ...,
       [ 323.53696596, -233.20101086,  -42.33964343],
       [ 324.52927402, -233.17487178,  -42.46064532],
       [ 325.52158208, -233.1487327 ,  -42.5816472 ]])

In [17]:
map.cur_map_points = I

In [18]:
map.add_to_base()

In [19]:
map.write_output_data()